version: '3'
services:
  test_component:
    restart: unless-stopped
    image: my-qanary-container
    build:
      context: .
      dockerfile: Dockerfile
    container_name: $SERVICE_NAME_COMPONENT
    ports:
      - $SERVICE_PORT:80
    environment:
      - SPRING_BOOT_ADMIN_URL=$SPRING_BOOT_ADMIN_URL
      - SPRING_BOOT_ADMIN_USERNAME=$SPRING_BOOT_ADMIN_USERNAME
      - SPRING_BOOT_ADMIN_PASSWORD=$SPRING_BOOT_ADMIN_PASSWORD
      - SERVICE_HOST=$SERVICE_HOST
      - SERVICE_PORT=$SERVICE_PORT
      - SERVICE_NAME_COMPONENT=$SERVICE_NAME_COMPONENT
      - SERVICE_DESCRIPTION_COMPONENT=$SERVICE_DESCRIPTION_COMPONENT
      - DEFAULT_ANSWER=$DEFAULT_ANSWER
    command: gunicorn -b :80 bert_qa_component:app